export enum MutationTypes {
  UPDATE_AUTHOR_DATA = "UPDATE_AUTHOR_DATA",
  UPDATE_AUTHOR_BOOK = "UPDATE_AUTHOR_BOOK",
  UPDATE_AUTHORS = "UPDATE_AUTHORS",
  REMOVE_AUTHOR = "REMOVE_AUTHOR",
  GET_AUTHORS = "GET_AUTHORS",
  GET_LAST_AUTHOR_ID = "GET_LAST_AUTHOR_ID",
}
